
%define WHITE_ON_BLACK 0x0F
%define BLACK_ON_WHITE 0xf0
%define WHITE_ON_GRAY 0x7f
%define FULL_GRAY 0x88

%define MAX_ROW 25
%define MAX_ROW_BOARD 24
%define MAX_COL 80

%define SCANCODE_REG 0x60
%define SCANCODE_EXT 0xe0
%define VIDEO_MEMORY 0xB8000
%define PIC_MASTER 0x20

%define UP_ARROW 0x48
%define DOWN_ARROW 0x50
%define LEFT_ARROW 0x4b
%define RIGHT_ARROW 0x4d

%define DEFAULT_SPEED 50
%define MIN_SPEED 0
%define MAX_SPEED 99
%define BASE_PIT_FREQ 1193180
%define BASE_FREQ 100

%define QUIT_QEMU 0x604
%define BACKSPACE 0x0E
%define ENTER 0x1C
%define MAX_INT_SIZE 12
