
%define VIDEO_MEMORY 0xB8000

%define WHITE_ON_BLACK 0x0F
%define BLACK_ON_WHITE 0xf0
%define WHITE_ON_GRAY 0x7f
%define FULL_GRAY 0x88

%define MAX_ROW 25
%define MAX_ROW_BOARD 24
%define MAX_COL 80

%define SCANCODE_REG 0x60
%define SCANCODE_EXT 0xe0

%define UP_ARROW 0x48
%define DOWN_ARROW 0x50
%define LEFT_ARROW 0x4b
%define RIGHT_ARROW 0x4d

%define BACKSPACE 0x0E
%define ENTER 0x1C
%define SC_MAX 57

%define PIC_MASTER 0x20
